# Generated by Django 3.2 on 2024-11-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20241113_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='012345', max_length=255, verbose_name='код подтверждения'),
        ),
    ]
